version: "1"
services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_DATABASE_URL=mongodb+srv://carlos:xcVb6Q9izLCTFExk@cluster0.fxnxa.mongodb.net/vpic?retryWrites=true&w=majority&appName=Cluster0
      - VPIC_API_URL=https://vpic.nhtsa.dot.gov/api/vehicles
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
